### ISSUE TITLE
vagrant installs old version

### ISSUE THREAD

**Issue by eriteric** [TypistTech/vagrant-trellis-cert#59]
`vagrant plugin install vagrant-trellis-cert` will install version 0.2.0.
running vagrant version 2.2.17
Tried manually downloading the latest, 0.5.2, but not sure how to build and install it that way.

**Comment by eriteric** [comment]
Found that the command is `gem build vagrant-trellis-cert.gemspec` to build, however i get errors when trying to install it

```
❯ vagrant plugin install vagrant-trellis-cert-0.5.2.gem
Installing the 'vagrant-trellis-cert-0.5.2.gem' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/conflict.rb:47:in `conflicting_dependencies': undefined method `request' for nil:NilClass (NoMethodError)
        from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/exceptions.rb:32:in `conflicting_dependencies'
        from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/exceptions.rb:26:in `initialize'
        from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `exception'
        from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `raise'
        from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `rescue in resolve'
        from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver.rb:191:in `resolve'
        from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/request_set.rb:411:in `resolve'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/bundler.rb:586:in `internal_install'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/bundler.rb:367:in `install_local'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/plugin/manager.rb:123:in `install_plugin'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/action/install_gem.rb:30:in `call'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/builder.rb:149:in `call'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/runner.rb:89:in `block in run'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/runner.rb:89:in `run'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/base.rb:14:in `action'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/install.rb:70:in `block in execute'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/install.rb:69:in `each'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/install.rb:69:in `execute'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/root.rb:66:in `execute'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/cli.rb:67:in `execute'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/environment.rb:290:in `cli'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/bin/vagrant:231:in `<main>'
/opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:317:in `raise_error_unless_state': Unable to satisfy the following requirements: (Gem::Resolver::Molinillo::VersionConflict)

- `vagrant-trellis-cert (= 0.5.2)` required by `user-specified dependency`
        from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
        from <internal:kernel>:90:in `tap'
        from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
        from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
        from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:254:in `process_topmost_state'
        from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
        from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
        from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver.rb:190:in `resolve'
        from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/request_set.rb:411:in `resolve'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/bundler.rb:586:in `internal_install'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/bundler.rb:367:in `install_local'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/plugin/manager.rb:123:in `install_plugin'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/action/install_gem.rb:30:in `call'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/builder.rb:149:in `call'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/runner.rb:89:in `block in run'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/runner.rb:89:in `run'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/base.rb:14:in `action'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/install.rb:70:in `block in execute'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/install.rb:69:in `each'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/install.rb:69:in `execute'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/root.rb:66:in `execute'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/cli.rb:67:in `execute'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/environment.rb:290:in `cli'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/bin/vagrant:231:in `<main>'

```
